version: '3'
services:
  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # Jaeger UI
      - "14250:14250" # Model used for gRPC
      - "14268:14268" # Model used for HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - otel-network

  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "8888:8888" # Prometheus metrics
      - "8889:8889" # Prometheus exporter metrics
    depends_on:
      - jaeger
    networks:
      - otel-network

networks:
  otel-network:
    driver: bridge
